USE MASTER
CREATE DATABASE QuanLyThuVien
USE QuanLyThuVien

--1
CREATE TABLE THEDOCGIA
(
	IDDocGia varchar(5) PRIMARY KEY NOT NULL,
	HoTenDG nvarchar(50) NOT NULL,
	NgaySinhDG datetime NOT NULL,
	DiaChiDG nvarchar(50) NOT NULL,
	EmailDG varchar(30) NOT NULL,
	IDLoaiDG nvarchar(5) FOREIGN KEY REFERENCES LOAIDOCGIA(IDLoaiDG),
	NgayLapThe datetime NOT NULL,
	NgayHetHan datetime,
	TongNo money DEFAULT(0)
)
DROP TABLE THEDOCGIA

--1.1
CREATE TABLE LOAIDOCGIA
(
	IDLoaiDG nvarchar(5) PRIMARY KEY NOT NULL,
	TenLoaiDG nvarchar(50) NOT NULL
)
DROP TABLE LOAIDOCGIA

--2
CREATE TABLE DAUSACH
(
	IDDauSach varchar(5) PRIMARY KEY NOT NULL,
	TenDauSach nvarchar(200) NOT NULL,
	IDLoaiSach varchar(5) FOREIGN KEY REFERENCES LOAISACH(IDLoaiSach)
)
DROP TABLE DAUSACH

--2.1
CREATE TABLE SACH
(
	IDSach varchar(5) PRIMARY KEY NOT NULL,
	IDDauSach varchar(5) FOREIGN KEY REFERENCES DAUSACH(IDDauSach),		
	NhaXB nvarchar(20) NOT NULL,
	NamXB int NOT NULL,	
	SoLuongTon int NOT NULL,
	GiaTien money NOT NULL
)
DROP TABLE SACH

--2.2
CREATE TABLE CUONSACH
(
	IDCuonSach varchar(5) PRIMARY KEY NOT NULL,
	IDSach varchar(5) FOREIGN KEY REFERENCES SACH(IDSach),
	TinhTrang nvarchar(20) NOT NULL
)
DROP TABLE CUONSACH

--2.3
CREATE TABLE LOAISACH
(
	IDLoaiSach varchar(5) PRIMARY KEY NOT NULL,
	TenLoaiSach nvarchar(50) NOT NULL
)
DROP TABLE LOAISACH

--2.4
CREATE TABLE CT_TACGIA
(
	IDCTTacGia varchar(5) PRIMARY KEY NOT NULL,
	IDDauSach varchar(5) FOREIGN KEY REFERENCES DAUSACH(IDDauSach),
	IDTacGia varchar(5) FOREIGN KEY REFERENCES TACGIA(IDTacGia)
)
DROP TABLE CT_TACGIA

--2.5
CREATE TABLE TACGIA
(
	IDTacGia nvarchar(5) PRIMARY KEY NOT NULL,
	TenTacGia nvarchar(50) NOT NULL,
	NgaySinh datetime
)
DROP TABLE TACGIA

--3
CREATE TABLE PHIEUNHAPSACH
(
	IDPhieuNhap varchar(5) PRIMARY KEY NOT NULL,
	NgayNhap datetime NOT NULL,
	TongTien money NOT NULL
)
DROP TABLE PHIEUNHAPSACH

--3.1
CREATE TABLE CT_PHIEUNHAPSACH
(
	IDCTPhieuNhap varchar(5) PRIMARY KEY NOT NULL,
	IDPhieuNhap varchar(5) FOREIGN KEY REFERENCES PHIEUNHAPSACH(IDPhieuNhap),
	IDSach varchar(5) FOREIGN KEY REFERENCES SACH(IDSach),
	SoLuong int NOT NULL,
	DonGia money NOT NULL,
	ThanhTien money NOT NULL
)
DROP TABLE CT_PHIEUNHAPSACH

--4
CREATE TABLE PHIEUMUON
(
	IDPhieuMuon varchar(5) PRIMARY KEY NOT NULL,	
	IDDocGia int FOREIGN KEY REFERENCES THEDOCGIA(IDDocGia),
	NgayMuon datetime NOT NULL,
	HanTra datetime NOT NULL
)
DROP TABLE PHIEUMUON

--4.1
CREATE TABLE CT_PHIEUMUON
(
	IDCTPhieuMuon varchar(5) PRIMARY KEY NOT NULL,
	IDPhieuMuon varchar(5) FOREIGN KEY REFERENCES PHIEUMUON(IDPhieuMuon),
	IDCuonSach varchar(5) FOREIGN KEY REFERENCES CUONSACH(IDCuonSach)	
)
DROP TABLE CT_PHIEUMUON

--5
CREATE TABLE PHIEUTRA
(
	IDPhieuTra varchar(5) PRIMARY KEY NOT NULL,
	IDDocGia int FOREIGN KEY REFERENCES THEDOCGIA(IDDocGia),
	NgayTra datetime NOT NULL,
	TienPhatKyNay money NOT NULL,
	SoTienTra money NOT NULL,
	TienNoKyNay money NOT NULL
)
DROP TABLE PHIEUTRA

--5.1
CREATE TABLE CT_PHIEUTRA
(
	IDCTPhieuTra varchar(5) PRIMARY KEY NOT NULL,
	IDPhieuTra varchar(5) FOREIGN KEY REFERENCES PHIEUTRA(IDPhieuTra),
	IDPhieuMuon varchar(5) FOREIGN KEY REFERENCES PHIEUMUON(IDPhieuMuon),
	SoNgayMuon int NOT NULL,
	TienPhat money
)
DROP TABLE CT_PHIEUTRA

--6
CREATE TABLE PHIEUTHUTIENPHAT
(
	IDPhieuThu varchar(5) PRIMARY KEY NOT NULL,	
	IDDocGia varchar(5) FOREIGN KEY REFERENCES DOCGIA(IDDocGia),
	NgayLap datetime NOT NULL,
	SoTienThu money NOT NULL,
	ConLai money NOT NULL
)
DROP TABLE PHIEUTHUTIENPHAT

--7
CREATE TABLE BCTINHHINHMUONSACH
(
	IDBCMuonSach varchar(5) PRIMARY KEY NOT NULL,
	ThangNam int NOT NULL,
	TongSoLuotMuon int NOT NULL
)
DROP TABLE BCTINHHINHMUONSACH

--7.1
CREATE TABLE CT_BCTINHHINHMUONSACH
(
	IDCTBCMuonSach varchar(5) PRIMARY KEY NOT NULL,
	IDBCMuonSach varchar(5) FOREIGN KEY REFERENCES BCMUONSACHTHEOTL(IDBCMuonSach),
	IDLoaiSach varchar(5) FOREIGN KEY REFERENCES LOAISACH(IDLoaiSach),
	SoLuotMuon int NOT NULL,
	TiLe float NOT NULL
)
DROP TABLE CT_BCTINHHINHMUONSACH

--8
CREATE TABLE BCSACHTRATRE
(
	IDBCSachTre varchar(5) PRIMARY KEY NOT NULL,
	NgayThangNam datetime NOT NULL,
	IDCuonSach  varchar(5) FOREIGN KEY REFERENCES CUONSACH(IDCuonSach),
	IDPhieuMuon varchar(5) FOREIGN KEY REFERENCES PHIEUMUON(IDPhieuMuon),
	SoNgayTraTre int NOT NULL
)
DROP TABLE BCSACHTRATRE

--9
CREATE TABLE THAMSO
(
	TuoiMin int,
	TuoiMax int,
	HanThe datetime,
	KhoangCachXB int,
	SoSachMuonMax int,
	SoNgayMuonMax int,
	TienPhatMoiNgay money,
	ApDungQDSoTienThu int
)
DROP TABLE THAMSO

--10
CREATE TABLE USERS
(
	UserName varchar(50) NOT NULL,
	IDDocGia int FOREIGN KEY REFERENCES THEDOCGIA(IDDocGia),
	Pwd varchar(50) NOT NULL
)
DROP TABLE USERS

SET DATEFORMAT dmy

ALTER TABLE THEDOCGIA ADD CONSTRAINT CK_LDG CHECK (LoaiDG IN(N'Thường', 'VIP'))
ALTER TABLE THEDOCGIA ADD CONSTRAINT CK_T CHECK (DATEDIFF(year, NgSinhDG, NgLapThe) BETWEEN 18 AND 55)
ALTER TABLE THEDOCGIA DROP CK_LDG
ALTER TABLE THEDOCGIA DROP CK_T

ALTER TABLE SACH ADD CONSTRAINT CK_TL CHECK (TheLoai IN(N'Truyện', N'Văn học dân gian', N'Văn học quốc tế'))
ALTER TABLE SACH ADD CONSTRAINT CK_XB CHECK ((year(NgNhap) - NamXB) <= 8)
ALTER TABLE SACH DROP CK_TL
ALTER TABLE SACH DROP CK_XB

-- Max 100 tác giả
CREATE TRIGGER TRG_TG ON SACH
FOR INSERT, UPDATE
AS
BEGIN
	IF((SELECT COUNT(DISTINCT TacGia) FROM SACH) > 100)
	BEGIN
		PRINT N'Lỗi: Vượt quá 100 tác giả'
		ROLLBACK TRANSACTION
	END
END

DROP TRIGGER TRG_TG

-- Tuổi độc giả
CREATE TRIGGER TRG_T ON THEDOCGIA
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGSINHDG datetime, @NGLAPTHE datetime
	
	SELECT @NGSINHDG = NgSinhDG, @NGLAPTHE = NgLapThe
	FROM INSERTED

	IF(DATEDIFF(year, @NGSINHDG, @NGLAPTHE) < 18 OR DATEDIFF(year, @NGSINHDG,  @NGLAPTHE) > 55)
	BEGIN
		PRINT N'Lỗi: Tuổi của độc giả phải từ 18 đến 55'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT N'Thành công'		
	END
END
			
DROP TRIGGER TRG_T								 

-- Ngày hết hạn
CREATE TRIGGER TRG_NHH ON THEDOCGIA
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGLAPTHE datetime
	
	SELECT @NGLAPTHE = NgLapThe
	FROM INSERTED
	
	UPDATE THEDOCGIA 
	SET NgHetHan = DATEADD(month, 6, @NGLAPTHE)
END

DROP TRIGGER TRG_NHH	

-- Mượn sách
CREATE TRIGGER TRG_MS ON PHIEUMUON
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @IDSACH varchar(5), @IDDOCGIA int, @NGAYMUON datetime, @TINHTRANG nvarchar(20), @NGHETHAN datetime
	
	SELECT @IDSACH = IDSach, @IDDOCGIA = IDDocGia, @NGAYMUON = NgayMuon
	FROM INSERTED
	SELECT @TINHTRANG = TinhTrang
	FROM SACH
	WHERE @IDSACH = IDSach
	SELECT @NGHETHAN = NgHetHan
	FROM THEDOCGIA
	WHERE @IDDOCGIA = IDDocGia

	IF((@TINHTRANG = N'Cho mượn') OR (@NGHETHAN <= @NGAYMUON) OR EXISTS (SELECT * FROM PHIEUMUON WHERE HanTra < @NGAYMUON))
	BEGIN
		PRINT N'Lỗi: Chỉ cho mượn với thẻ còn hạn, không có sách mượn quá hạn, và sách không có người đang mượn'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT N'Thành công'
	END
END

DROP TRIGGER TRG_MS

-- Max Mượn
CREATE TRIGGER TRG_MM ON PHIEUMUON
FOR INSERT
AS
BEGIN
	DECLARE @IDDOCGIA int

	SELECT @IDDOCGIA = IDDocGia
	FROM INSERTED

	IF((SELECT COUNT(DISTINCT IDSach) FROM PHIEUMUON WHERE @IDDOCGIA = IDDocGia) > 5)
	BEGIN
		PRINT N'Lỗi: Mỗi độc giả mượn tối đa 5 quyển sách'
		ROLLBACK TRANSACTION 
	END
	ELSE
	BEGIN
		PRINT N'Thành công'
	END
END

DROP TRIGGER TRG_MM

-- Hạn trả
CREATE TRIGGER TRG_HT ON PHIEUMUON
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGAYMUON datetime
	
	SELECT @NGAYMUON = NgayMuon
	FROM INSERTED
	
	UPDATE PHIEUMUON
	SET HanTra = DATEADD(day, 4, @NGAYMUON)
END

DROP TRIGGER TRG_HT
