USE MASTER
CREATE DATABASE QuanLyThuVien
USE QuanLyThuVien

--1
CREATE TABLE THEDOCGIA
(
	IDDocGia varchar(5) PRIMARY KEY NOT NULL,
	HoTenDG nvarchar(50) NOT NULL,
	NgSinhDG datetime NOT NULL,
	DiaChiDG nvarchar(50) NOT NULL,
	EmailDG varchar(30) NOT NULL,
	IDLoaiDG nvarchar(5) FOREIGN KEY REFERENCES LOAIDOCGIA(IDLoaiDG),
	NgLapThe datetime NOT NULL,
	NgHetHan datetime,
	TongNo money DEFAULT(0)
)
DROP TABLE THEDOCGIA

--2
CREATE TABLE LOAIDOCGIA
(
	IDLoaiDG nvarchar(5) PRIMARY KEY NOT NULL,
	TenLoaiDG nvarchar(50) NOT NULL
)
DROP TABLE LOAIDOCGIA

--3
CREATE TABLE SACH
(
	IDSach varchar(5) PRIMARY KEY NOT NULL,
	TenSach nvarchar(200) NOT NULL,
	IDLoaiSach varchar(5) FOREIGN KEY REFERENCES LOAISACH(IDLoaiSach),
	IDTacGia varchar(5) FOREIGN KEY REFERENCES TACGIA(IDTacGia),
	NamXB int NOT NULL,
	NhaXB nvarchar(20) NOT NULL,
	NgNhap datetime NOT NULL,
	TriGia money NOT NULL,
	TinhTrang nvarchar(20)	
)
DROP TABLE SACH

--4
CREATE TABLE LOAISACH
(
	IDLoaiSach varchar(5) PRIMARY KEY NOT NULL,
	TenLoaiSach nvarchar(50) NOT NULL
)
DROP TABLE LOAISACH

--5
CREATE TABLE TACGIA
(
	IDTacGia nvarchar(5) PRIMARY KEY NOT NULL,
	TenTacGia nvarchar(50) NOT NULL
)
DROP TABLE TACGIA

--6
CREATE TABLE PHIEUMUON
(
	IDPhieuMuon varchar(5) PRIMARY KEY NOT NULL,	
	IDDocGia int FOREIGN KEY REFERENCES THEDOCGIA(IDDocGia),
	NgayMuon datetime NOT NULL,
	HanTra datetime NOT NULL
)
DROP TABLE PHIEUMUON

--7
CREATE TABLE CTPHIEUMUON
(
	IDCTPhieuMuon varchar(5) PRIMARY KEY NOT NULL,
	IDPhieuMuon varchar(5) FOREIGN KEY REFERENCES PHIEUMUON(IDPhieuMuon),
	IDSach varchar(5) FOREIGN KEY REFERENCES SACH(IDSach)
)
DROP TABLE CTPHIEUMUON

--8
CREATE TABLE PHIEUTRA
(
	IDPhieuTra varchar(5) PRIMARY KEY NOT NULL,
	IDDocGia int FOREIGN KEY REFERENCES THEDOCGIA(IDDocGia),
	NgayTra datetime NOT NULL,
	TienPhatKN money,
)
DROP TABLE PHIEUTRA

--9
CREATE TABLE CTPHIEUTRA
(
	IDCTPhieuTra varchar(5) PRIMARY KEY NOT NULL,
	IDPhieuTra varchar(5) FOREIGN KEY REFERENCES PHIEUTRA(IDPhieuTra),
	IDCTPhieuMuon varchar(5) FOREIGN KEY REFERENCES CTPHIEUMUON(IDCTPhieuMuon),
	SoNgMuon int,
	TienPhat money
)
DROP TABLE CTPHIEUTRA

--10
CREATE TABLE PHIEUTIENPHAT
(
	IDPhieuPhat varchar(5) PRIMARY KEY NOT NULL,
	IDPhieuTra varchar(5) FOREIGN KEY REFERENCES PHIEUTRA(IDPhieuTra),
	SoTienThu money,
	ConLai money
)
DROP TABLE PHIEUTIENPHAT

--11
CREATE TABLE BCMUONSACHTHEOTL
(
	IDBCMuonSach varchar(5) PRIMARY KEY NOT NULL,
	Thang int,
	TongSoLuotMuon int
)
DROP TABLE BCMUONSACHTHEOTL

--12
CREATE TABLE CTBCMUONSACHTHEOTL
(
	IDCTBCMuonSach varchar(5) PRIMARY KEY NOT NULL,
	IDBCMuonSach varchar(5) FOREIGN KEY REFERENCES BCMUONSACHTHEOTL(IDBCMuonSach),
	IDLoaiSach varchar(5) FOREIGN KEY REFERENCES LOAISACH(IDLoaiSach),
	SoLuotMuon int,
	TiLe float
)
DROP TABLE CTBCMUONSACHTHEOTL

--13
CREATE TABLE BCSACHTRATRE
(
	IDBCSachTre varchar(5) PRIMARY KEY NOT NULL,
	Ngay int,
	IDCTPhieuMuon varchar(5) FOREIGN KEY REFERENCES CTPHIEUMUON(IDCTPhieuMuon),
	IDCTPhieuTra varchar(5) FOREIGN KEY REFERENCES CTPHIEUTRA(IDCTPhieuTra)
)
DROP TABLE BCSACHTRATRE

--14
CREATE TABLE THAMSO
(
	TuoiMin int,
	TuoiMax int,
	HanThe datetime,
	KhoangCachXB int,
	SLMuonMax int,
	TGianMuonMax int,
	SLTacGia int,
	TienPhat1Ngay money
)
DROP TABLE THAMSO

--15
CREATE TABLE USERS
(
	UserName varchar(50) NOT NULL,
	IDDocGia int FOREIGN KEY REFERENCES THEDOCGIA(IDDocGia),
	Pwd varchar(50) NOT NULL
)
DROP TABLE USERS

SET DATEFORMAT dmy

ALTER TABLE THEDOCGIA ADD CONSTRAINT CK_LDG CHECK (LoaiDG IN(N'Thường', 'VIP'))
ALTER TABLE THEDOCGIA ADD CONSTRAINT CK_T CHECK (DATEDIFF(year, NgSinhDG, NgLapThe) BETWEEN 18 AND 55)
ALTER TABLE THEDOCGIA DROP CK_LDG
ALTER TABLE THEDOCGIA DROP CK_T

ALTER TABLE SACH ADD CONSTRAINT CK_TL CHECK (TheLoai IN(N'Truyện', N'Văn học dân gian', N'Văn học quốc tế'))
ALTER TABLE SACH ADD CONSTRAINT CK_XB CHECK ((year(NgNhap) - NamXB) <= 8)
ALTER TABLE SACH DROP CK_TL
ALTER TABLE SACH DROP CK_XB

-- Max 100 tác giả
CREATE TRIGGER TRG_TG ON SACH
FOR INSERT, UPDATE
AS
BEGIN
	IF((SELECT COUNT(DISTINCT TacGia) FROM SACH) > 100)
	BEGIN
		PRINT N'Lỗi: Vượt quá 100 tác giả'
		ROLLBACK TRANSACTION
	END
END

DROP TRIGGER TRG_TG

-- Tuổi độc giả
CREATE TRIGGER TRG_T ON THEDOCGIA
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGSINHDG datetime, @NGLAPTHE datetime
	
	SELECT @NGSINHDG = NgSinhDG, @NGLAPTHE = NgLapThe
	FROM INSERTED

	IF(DATEDIFF(year, @NGSINHDG, @NGLAPTHE) < 18 OR DATEDIFF(year, @NGSINHDG,  @NGLAPTHE) > 55)
	BEGIN
		PRINT N'Lỗi: Tuổi của độc giả phải từ 18 đến 55'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT N'Thành công'		
	END
END
			
DROP TRIGGER TRG_T								 

-- Ngày hết hạn
CREATE TRIGGER TRG_NHH ON THEDOCGIA
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGLAPTHE datetime
	
	SELECT @NGLAPTHE = NgLapThe
	FROM INSERTED
	
	UPDATE THEDOCGIA 
	SET NgHetHan = DATEADD(month, 6, @NGLAPTHE)
END

DROP TRIGGER TRG_NHH	

-- Mượn sách
CREATE TRIGGER TRG_MS ON PHIEUMUON
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @IDSACH varchar(5), @IDDOCGIA int, @NGAYMUON datetime, @TINHTRANG nvarchar(20), @NGHETHAN datetime
	
	SELECT @IDSACH = IDSach, @IDDOCGIA = IDDocGia, @NGAYMUON = NgayMuon
	FROM INSERTED
	SELECT @TINHTRANG = TinhTrang
	FROM SACH
	WHERE @IDSACH = IDSach
	SELECT @NGHETHAN = NgHetHan
	FROM THEDOCGIA
	WHERE @IDDOCGIA = IDDocGia

	IF((@TINHTRANG = N'Cho mượn') OR (@NGHETHAN <= @NGAYMUON) OR EXISTS (SELECT * FROM PHIEUMUON WHERE HanTra < @NGAYMUON))
	BEGIN
		PRINT N'Lỗi: Chỉ cho mượn với thẻ còn hạn, không có sách mượn quá hạn, và sách không có người đang mượn'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT N'Thành công'
	END
END

DROP TRIGGER TRG_MS

-- Max Mượn
CREATE TRIGGER TRG_MM ON PHIEUMUON
FOR INSERT
AS
BEGIN
	DECLARE @IDDOCGIA int

	SELECT @IDDOCGIA = IDDocGia
	FROM INSERTED

	IF((SELECT COUNT(DISTINCT IDSach) FROM PHIEUMUON WHERE @IDDOCGIA = IDDocGia) > 5)
	BEGIN
		PRINT N'Lỗi: Mỗi độc giả mượn tối đa 5 quyển sách'
		ROLLBACK TRANSACTION 
	END
	ELSE
	BEGIN
		PRINT N'Thành công'
	END
END

DROP TRIGGER TRG_MM

-- Hạn trả
CREATE TRIGGER TRG_HT ON PHIEUMUON
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGAYMUON datetime
	
	SELECT @NGAYMUON = NgayMuon
	FROM INSERTED
	
	UPDATE PHIEUMUON
	SET HanTra = DATEADD(day, 4, @NGAYMUON)
END

DROP TRIGGER TRG_HT
